[tool.poetry]
name = " Telecom Eda-app"
version = "1.0.0"
description = ""
authors = ["Ranjan Singh"]

[tool.poetry.dependencies]
python = "^3.8" 

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
